const mongoose = require('mongoose')

const detailSchema = mongoose.Schema({
    id: { type: String, required: true },
    name: { type: String, required: true },
    view: { type: String, required: true },
    image1: { type: String, required: true },
    image2: { type: String, required: true },
    image3: { type: String, required: true },
    describe: { type: String, required: true },
    location: { type: String, required: true },
    email: { type: String, required: true },
    phone: { type: String, required: true },
    locationSrc: { type: String, required: true },
    imageSimilar1: { type: String },
    similar1: { type: String },
    imageSimilar2: { type: String },
    similar2: { type: String },
    imageSimilar3: { type: String },
    similar3: { type: String },
    imageSimilar4: { type: String },
    similar4: { type: String },
    star: { type: String, required: true },
    poppular1: { type: String },
    poppular2: { type: String },
    poppular3: { type: String },
    poppular4: { type: String },
    poppular5: { type: String },
    poppular6: { type: String },
    poppular7: { type: String },
    personSrc1: { type: String },
    person1: { type: String },
    personText1: { type: String },
    imageReview11: { type: String },
    imageReview12: { type: String },
    personSrc2: { type: String },
    person2: { type: String },
    personText2: { type: String },
    imageReview21: { type: String },
    imageReview22: { type: String },
    imageReview23: { type: String },
    personSrc3: { type: String },
    person3: { type: String },
    personText3: { type: String },
    imageReview31: { type: String },
    imageReview32: { type: String }
},{timestamps: true})

module.exports = mongoose.model('detail', detailSchema)